CC = gcc
CFLAGS = -Wall -Wextra -std=c11
TARGET = program

all: $(TARGET)

$(TARGET): main.o func.o
	$(CC) $(CFLAGS) -o $@ $^

main.o: main.c
	$(CC) $(CFLAGS) -c $<

func.o: func.c
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f $(TARGET) *.o

